#!/bin/bash
#
#       /etc/rc.d/init.d/
#
#
#
#
#

# Source function library.
. /etc/init.d/functions



start() {
        echo -n "Starting : Crypto Currency Tracker"
	/home/pi/wp14-raspberry-pi-crypto-currency-tracker/cryto_currency_monitor
        touch /var/lock/subsys/
        return
}

stop() {
        echo -n "Shutting down : Crypto Currency Tracker"
	killall cryto_currency_monitor
        rm -f /var/lock/subsys/
        return
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)

        ;;
    restart)
        stop
        start
        ;;
    reload)

tart)

        [ -f /var/lock/subsys/ ] && restart || :
    probe)

        ;;
    *)
        echo "Usage:  {start|stop|status|reload|restart[|probe]"
        exit 1
        ;;
esac
exit $?
